extends RefCounted

# Copias intactas de los originales, identificadas por ID y nombre de carta.
const PATHS := {
	"H001": "res://assets/cards/humanos/H001_balas_de_plata.png",
	"H002": "res://assets/cards/humanos/H002_cruz_sagrada.png",
	"H003": "res://assets/cards/humanos/H003_aldeano_valiente.png",
	"H004": "res://assets/cards/humanos/H004_trampa_para_lobos.png",
	"H005": "res://assets/cards/humanos/H005_campana_de_la_iglesia.png",
	"H006": "res://assets/cards/humanos/H006_milicia_organizada.png",
	"H007": "res://assets/cards/humanos/H007_antorcha_ardiente.png",
	"H008": "res://assets/cards/humanos/H008_cazador_experto.png",
	"H009": "res://assets/cards/humanos/H009_heroe_local.png",
	"H010": "res://assets/cards/humanos/H010_barricada.png",
	"L001": "res://assets/cards/hombres_lobo/L001_garra_salvaje.png",
	"L002": "res://assets/cards/hombres_lobo/L002_aullido.png",
	"L003": "res://assets/cards/hombres_lobo/L003_alfa_dominante.png",
	"L004": "res://assets/cards/hombres_lobo/L004_mordida_rabiosa.png",
	"L005": "res://assets/cards/hombres_lobo/L005_manada_feroz.png",
	"L006": "res://assets/cards/hombres_lobo/L006_colmillo_venenoso.png",
	"L007": "res://assets/cards/hombres_lobo/L007_luna_llena.png",
	"L008": "res://assets/cards/hombres_lobo/L008_lobo_solitario.png",
	"L018": "res://assets/cards/hombres_lobo/L018_pista_de_presa.png",
	"L029": "res://assets/cards/hombres_lobo/L029_piel_gruesa.png",
	"V001": "res://assets/cards/vampiros/V001_mordisco_vampirico.png",
	"V002": "res://assets/cards/vampiros/V002_niebla_eterna.png",
	"V003": "res://assets/cards/vampiros/V003_sed_insaciable.png",
	"V004": "res://assets/cards/vampiros/V004_murcielago_espia.png",
	"V005": "res://assets/cards/vampiros/V005_drenaje_vital.png",
	"V006": "res://assets/cards/vampiros/V006_colmillo_noble.png",
	"V007": "res://assets/cards/vampiros/V007_velo_de_sombras.png",
	"V008": "res://assets/cards/vampiros/V008_conversion.png",
	"V009": "res://assets/cards/vampiros/V009_hipnosis_mental.png",
	"V014": "res://assets/cards/vampiros/V014_sangre_pura.png",
	"F001": "res://assets/cards/fantasmas/F001_susurro_espectral.png",
	"F002": "res://assets/cards/fantasmas/F002_posesion_leve.png",
	"F003": "res://assets/cards/fantasmas/F003_velo_fantasmal.png",
	"F004": "res://assets/cards/fantasmas/F004_ectoplasma_frio.png",
	"F005": "res://assets/cards/fantasmas/F005_aparicion_subita.png",
	"F006": "res://assets/cards/fantasmas/F006_cadena_eterea.png",
	"F007": "res://assets/cards/fantasmas/F007_lamento_nocturno.png",
	"F008": "res://assets/cards/fantasmas/F008_paso_a_traves.png",
	"F009": "res://assets/cards/fantasmas/F009_toque_gelido.png",
	"F015": "res://assets/cards/fantasmas/F015_eco_del_pasado.png",
}
