extends RefCounted

# These close the prototype route, not the planned full campaign.
const ENDINGS := {
	"Humanos": {"title": "Los nombres del alba", "text": "Inés baja las escaleras de Santa Vigilia con el libro del Custodio bajo el brazo. Entre sus páginas encuentra la firma de su padre y una lista de vecinos que nadie quiso buscar.\n\nEn la plaza no promete que el peligro haya terminado. Pide una mesa, lámparas y manos dispuestas a copiar cada nombre. Por primera vez desde la Desvelada, alguien abre una puerta para escuchar a quienes siguen fuera.\n\nBajo el monasterio, el Corazón Hueco aún late. Esta noche tendrá que hacerlo sin el silencio de todos."},
	"Hombres Lobo": {"title": "El último de la manada", "text": "Tomás podría reclamar Santa Vigilia como territorio de la manada. En lugar de hacerlo, deja las puertas abiertas y sigue el rastro de los rezagados.\n\nCuando llega a la sierra, el primero en acercarse es un lobezno que no consigue volver a su forma humana. Tomás se sienta a su lado y espera. No hay desafío ni orden: solo dos respiraciones que aprenden a acompasarse.\n\nLa luna negra no ha desaparecido. Pero esa noche ningún miembro de la manada la mira a solas."},
	"Vampiros": {"title": "Una deuda sin dueño", "text": "Leonor encuentra en Santa Vigilia un registro de tributos: sangre entregada como si las personas fueran tierras de una herencia. Reconoce el sello de su casa.\n\nSe lleva el registro al palacio y lo abre ante quienes lo sostuvieron durante generaciones. No pide perdón en nombre de los muertos ni obediencia en nombre de los vivos. Ofrece devolver lo que todavía pueda devolverse.\n\nBaltasar no responderá con gratitud. El Corazón Hueco tampoco. Por primera vez, esa certeza no decide por ella."},
	"Fantasmas": {"title": "Mensaje recibido", "text": "Clara alcanza el telégrafo de la estación cuando el primer tren de auxilio se detiene ante el túnel. Sus dedos no pueden mover la llave, pero los cables aún recuerdan su voz.\n\nEnvía los nombres de los muertos, uno por uno. Al otro extremo, un operador deja de pedir identificación y empieza a escribir.\n\nLa última respuesta atraviesa la niebla: «Recibido». Clara no recupera todos sus recuerdos ni abandona este mundo. Sin embargo, por un instante, los ausentes dejan de ser una cifra."}
}
